### ISSUE TITLE
Unable to load with The Lounge 3.2.0 installed via apt on Debian 10

### ISSUE THREAD

**Issue by tewan** [MiniDigger/thelounge-plugin-shortcuts#10]
Getting the following error in syslog when starting thelounge that was installed using apt on Debian 10.
[WARN] Package thelounge-plugin-shortcuts could not be loaded

Tried 1.0.2 and yielded same issue. Tried enabling debug modes in thelounge config but didn't get any additional useful data.

**Comment by MiniDigger** [comment]
Mmmh, do you get that for installing any packages? Have you ever installed a package before (even just a theme)? Can you try using this theme as an example https://github.com/MiniDigger/thelounge-theme-mininapse

**Comment by tewan** [comment]
No, actually have installed all themes because I wasn't sure which I'd like most. 

`Oct 21 02:34:18 sharing systemd[1]: Started The Lounge (IRC client).
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] The Lounge v3.2.0 (Node.js 10.15.2 on linux x64)
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Configuration file: /etc/thelounge/config.js
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Available at http://:::9000/ in private mode
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [WARN] Package thelounge-plugin-shortcuts could not be loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-abyss loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-amoled loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-bdefault loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-bmorning loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-classic loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-common loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-crypto loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-dracula loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-gruvbox loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-hexified loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-ion loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-light loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-material loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-mininapse loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-mortified loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-neuron-fork loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-onedark loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-purplenight loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-scoutlink loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-solarized loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-solarized-fork-monospace loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-zenburn loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] Package thelounge-theme-zenburn-monospace loaded
Oct 21 02:34:19 sharing thelounge[1464]: 2019-10-21 02:34:19 [INFO] User tewan loaded`

**Comment by MiniDigger** [comment]
Can you try with 3.3.0 RC1 that was just released? It includes https://github.com/thelounge/thelounge/pull/3406 which helps looking into theses issues.
As I developed the theme against master I wouldn't be surprised if it wouldn't load on 3.2.

**Comment by tewan** [comment]
Didn't load but got some more useful info this time.

```
Oct 21 16:55:36 sharing thelounge[22609]: 2019-10-21 16:55:36 [ERROR] Package thelounge-plugin-shortcuts could not be loaded: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
Oct 21 16:55:36 sharing thelounge[22609]: 2019-10-21 16:55:36 [DEBUG] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
Oct 21 16:55:36 sharing thelounge[22609]:     at validateString (internal/validators.js:112:11)
Oct 21 16:55:36 sharing thelounge[22609]:     at Object.resolve (path.js:981:7)
Oct 21 16:55:36 sharing thelounge[22609]:     at Object.<anonymous> (/etc/thelounge/packages/node_modules/thelounge-plugin-shortcuts/index.js:8:28)
Oct 21 16:55:36 sharing thelounge[22609]:     at Module._compile (internal/modules/cjs/loader.js:945:30)
Oct 21 16:55:36 sharing thelounge[22609]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
Oct 21 16:55:36 sharing thelounge[22609]:     at Module.load (internal/modules/cjs/loader.js:798:32)
Oct 21 16:55:36 sharing thelounge[22609]:     at Function.Module._load (internal/modules/cjs/loader.js:711:12)
Oct 21 16:55:36 sharing thelounge[22609]:     at Module.require (internal/modules/cjs/loader.js:838:19)
Oct 21 16:55:36 sharing thelounge[22609]:     at require (internal/modules/cjs/helpers.js:74:18)
Oct 21 16:55:36 sharing thelounge[22609]:     at /usr/lib/node_modules/thelounge/src/plugins/packages/index.js:93:18
```

**Comment by MiniDigger** [comment]
ahh, yeah, I forgot about that thing last week but I fixed it earlier: https://github.com/MiniDigger/thelounge-plugin-shortcuts/commit/e65dcd93877d72209debb443a22270cbb13003f9
Ill publish to npm later

**Comment by MiniDigger** [comment]
version v1.0.4 should address this, can you confirm?

**Comment by tewan** [comment]
Plugin loads now however it is throwing an error on startup. 

```
Oct 21 20:04:31 sharing thelounge[2658]: 2019-10-21 20:04:31 [ERROR] [Error: EACCES: permission denied, open '/home/thelounge/.thelounge/packages/shortcuts.json'] {
Oct 21 20:04:31 sharing thelounge[2658]:   errno: -13,
Oct 21 20:04:31 sharing thelounge[2658]:   code: 'EACCES',
Oct 21 20:04:31 sharing thelounge[2658]:   syscall: 'open',
Oct 21 20:04:31 sharing thelounge[2658]:   path: '/home/thelounge/.thelounge/packages/shortcuts.json'
Oct 21 20:04:31 sharing thelounge[2658]: }
```

I am able to use /shortcut in The Lounge and add as well as use but whenever restarting the service it loses settings. I tried creating a the referenced directory and touching shortcuts.json then setting owner/group to thelounge (what it's running under) but it is still throwing the same error code.

**Comment by MiniDigger** [comment]
since I am a noob system admin I cant really help you with this and I am gonna close this. The error clearly indicates a permission problem so I dont think there is anything wrong on the plugin side.
